name: generate

on:
  release:
    types: [released]

jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  # fern-release:
  #   needs: fern-check
  #   if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup node
  #       uses: actions/setup-node@v3

  #     - name: Download Fern
  #       run: npm install -g fern-api

  #     - name: Release SDKs
  #       env:
  #         FERN_NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}
  #         FERN_MAVEN_USERNAME: ${{ secrets.FERN_MAVEN_USERNAME }}
  #         FERN_MAVEN_TOKEN: ${{ secrets.FERN_MAVEN_TOKEN }}
  #       run: fern generate --group external --version ${{ github.ref_name }} --log-level debug
